name: flamingo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  shared_preferences: ^2.5.5
  sensors_plus: ^7.0.0
  vibration: ^3.1.8
  torch_light: ^1.0.0
  flutter_local_notifications: ^19.4.1
  mobile_scanner: ^7.0.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.0
  build_runner: ^2.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
